tree: Events
eras:
  '2022':
    luminosity: 2000
dbcache: dascache
samples:
  QCD_Flat:
    era: '2022'
    group: QCD_Flat
    files: /home/ucl/cp3/gmauceri/jme-validation/datasets/QCD_Summer23_fromPV4GeV_v2.txt
    type: mc
    split: 100
    campaign: Summer22EEFromPV2Tau4GeV
    jec: Summer22EERun3_V0_MC
    jec_level: default
    jec_algo_AK4: Puppi
    jec_algo_AK8: Puppi
    withCHS: false
    plot_level: all
    cross-section: 1859000000
    generated-events: genEventSumw
plotIt:
  configuration:
    width: 800
    height: 600
    margin-left: 0.2
    margin-right: 0.03
    margin-top: 0.05
    margin-bottom: 0.15
    luminosity-label: 2022, %1$.2f fb^-1 (13.6 TeV)
    experiment: CMS
    extra-label: Work in progress
    error-fill-style: 3154
    error-fill-color: '#ee556270'
    ratio-fit-error-fill-style: 1001
    ratio-fit-error-fill-color: '#aa556270'
    ratio-fit-line-color: '#0B486B'
    yields-table-align: v
  legend:
    position:
    - 0.7
    - 0.6
    - 0.91
    - 0.91
  groups:
    data:
      legend: data
    DY:
      legend: DY
      fill-color: '#609e1b'
    TTbar:
      legend: TTbar
      fill-color: '#99ccff'
    QCD_Flat:
      legend: QCD
      fill-color: '#FFC300'
    WJets:
      legend: WJets
      fill-color: '#9c04c4'
  plotdefaults:
    y-axis: Events
    log-y: both
    y-axis-show-zero: true
    save-extensions:
    - pdf
    show-ratio: true
    sort-by-yields: true
    legend-columns: 2
    ratio-y-axis: '#frac{Data}{MC}'
    ratio-y-axis-range:
    - 0.8
    - 1.2
    normalized: true
